name: CI

on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  ci:
    uses: RawZ06-Studio/.github/.github/workflows/maven-ci.yml@main
    with:
      java_version: '25'
    secrets:
      NEXUS_LOGIN: ${{ secrets.NEXUS_LOGIN }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  sonar:
    needs: ci
    uses: RawZ06-Studio/.github/.github/workflows/maven-ci-sonar.yml@main
    with:
      java_version: '25'
      sonar_project_key: 'Rawz06-Studio_RSLFrancoBot_af333436-4fc6-4040-842f-a594a39a07dc'
      sonar_project_name: 'RSLFrancoBot'
    secrets:
      NEXUS_LOGIN: ${{ secrets.NEXUS_LOGIN }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
